trigger:
  branches:
    include:
      - main

variables:
  # Update these with your values
  acrName: 'myacrregistryrishi'
  acrLoginServer: 'myacrregistryrishi.azurecr.io'
  imageName: 'microservice-b'
  imageTag: 'latest'
  aksClusterName: 'MyAKSCluster'
  aksResourceGroup: 'MyResourceGroup'
  azureSubscription: 'azureConnection2'  # name of the service connection in DevOps, created while creating service connection name in project Settings> connection

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: 'buildAndPush'
        repository: '$(acrLoginServer)/$(imageName)'
        Dockerfile: '**/Dockerfile'
        containerRegistry: '$(azureSubscription)'
        tags: |
          $(imageTag)

- stage: DeployToAKS
  displayName: 'Deploy to AKS'
  dependsOn: BuildAndPush
  jobs:
  - deployment: Deploy
    displayName: 'Deploy microservice-b to AKS'
    environment: 'aks-env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Deploy to AKS'
            inputs:
              azureSubscription: '$(azureSubscription)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName)
                kubectl apply -f microservice-b-deployment.yml
                kubectl apply -f microservice-b-service.yml