apiVersion: v1
kind: Service
metadata:
  name: microservice-test-service
spec:
  selector:
    app: microservice-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292
  type: LoadBalancer