apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-test
  template:
    metadata:
      labels:
        app: microservice-test
    spec:
      containers:
      - name: microservice-test
        image: myacrregistryrishi2.azurecr.io/microservice-test:latest
        ports:
        - containerPort: 9292