apiVersion: v1
kind: Service
metadata:
    name: rishikumarspringbootcrudappazure
spec:
    type: LoadBalancer
    ports:
    - port: 9292 
    selector:
        app: rishikumarspringbootcrudappazure